---
kind: Service
apiVersion: v1
metadata:
  name: react-app-nlb
  namespace: ${NAMESPACE}
  labels:
    area: react
    tier: app
spec:
  selector:
    area: react
    tier: app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: react-app
  namespace: ${NAMESPACE}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        area: react
        tier: app
    spec:
      containers:
      - name: reactapp
        image: gcr.io/${PROJECT}/reactapp:latest
        ports:
        - name: http
          containerPort: 8080  
        
